spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: mad-api
  datasource:
    url: jdbc:postgresql://${MAD_DB_HOST}:${MAD_DB_PORT}/${MAD_DB_NAME}
    username: ${MAD_DB_USERNAME}
    password: ${MAD_DB_PASSWORD}
  flyway:
    default-schema: mad_db
    enabled: true
    locations: classpath:db/migration
    schemas: mad_db
    validate-migration-naming: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      "[hibernate.default_schema]": mad_db

management:
  endpoints:
    web:
      exposure:
        include: health,info
